BookStore/BookStore/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

BookStore/book/urls.py
from django.urls import path
from book.views import BookListView, BooksDetailView, BooksCreateView, BooksUpdateView, BooksDeleteView \

app_name = "book"

urlpatterns = [
    path('', BooksListView.as_view(), name = 'book'),
    path('detail/<int:pk>/', BooksDetailView.as_view(), name = 'book_detail'),
    path('create/', BooksCreateView.as_view(), name = 'book_create'),
    path('update/<int:pk>/', BooksUpdateView.as_view(), name = 'book_update'),
    path('delete/<int:pk>/', BooksDeleteView.as_view(), name = 'book_delete'),
]

BookStore/refers/urls.py
from django.urls import path
from refers.views import AuthorListView, AuthorDetailView, AuthorCreateView, AuthorDeleteView, AuthorUpdateView, \
    SerieListView, SerieDetailView, SerieCreateView, SerieDeleteView, SerieUpdateView, GenreListView, \
    GenreDetailView, GenreCreateView, GenreUpdateView, GenreDeleteView

app_name = "refers"

urlpatterns = [
    path('authors/', AuthorListView.as_view(), name='authors'),
    path('<int:pk>/', views.AuthorDetailView.as_view(), name='authors_detail'),
    path('authors/create/', views.AuthorCreateView.as_view(), name='authors_create'),
    path('delete/<int:pk>/', views.AuthorDeleteView.as_view(), name='authors_delete'),
    path('update/<int:pk>/', views.AuthorUpdateView.as_view(), name='authors_update'),
    path('series/', views.SerieListView.as_view(), name='series'),
    path('<int:pk>/', views.SerieDetailView.as_view(), name='series_detail'),
    path('series/create/', views.SerieCreateView.as_view(), name='series_create'),
    path('delete/<int:pk>/', views.SerieDeleteView.as_view(), name='series_delete'),
    path('update/<int:pk>/', views.SerieUpdateView.as_view(), name='series_update'),
    path('genres/', views.GenreListView.as_view(), name='genres'),
    path('<int:pk>/', views.GenreDetailView.as_view(), name='genres_detail'),
    path('genres/create/', views.GenreCreateView.as_view(), name='genres_create'),
    path('delete/<int:pk>/', views.GenreDeleteView.as_view(), name='genres_delete'),
    path('update/<int:pk>/', views.GenreUpdateView.as_view(), name='genres_update'),
]

BookStore/book/models.py
from django.db import models
from refers.models import Author,Serie,Genre

class Book(models.Model):
    title = models.CharField(max_length=100,blank=False, null=False)
    description = models.CharField(max_length=500,blank=True)
    cover = models.ImageField(upload_to='', blank=True)
    isbn = models.CharField(max_length=100, blank=True)
    author = models.ManyToManyField(
        Author,
    )
    serie = models.ForeignKey(
        Serie,
        on_delete=models.PROTECT
    )
    genre = models.ManyToManyField(
        Genre,
    )
    price = models.DecimalField(max_digits=5, decimal_places=2)
    cataloging = models.DateField(auto_now_add=True)
    last_change = models.DateField(auto_now=True)
    available_order = models.BooleanField(default=True)
    quantity = models.PositiveIntegerField(max_length=10)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name= "Book"
        verbose_name_plural = "Books"

    def get_absolute_url(self):
        return '/books/{self.pk}'

BookStore/users/models.py
from django.db import models
from django.contrib.auth.models import Users
from django.dispatch import receiver
from django.db.models.signals import post_save

class Profile(models.Model):
    user = models.OneToOneField(
        User,
        related_name='profile',
        on_delete=models.CASCADE
    )
    location = models.CharField(max_length=30, blank=True)

@receiver(post_save, sender = User)
def profile_for_new_user(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance).save()

BookStore/users/forms.py
from django.contrib.auth.models import User
from django import forms

class RegisterForm(forms.ModelForm):
    location = forms.CharField()

    class Meta:
        model = User
        fields = (
            'username',
            'email',
            'first_name',
            'last_name',
            'password'
        )

BookStore/users/views.py
from django.shortcuts import render
from django.views.generic import DetailView, FormView
from django.db import models
from .models import Profile
from .forms import RegisterForm
from django.contrib.auth.models import User
from django.http import HttpResponse

class CreateProfileView(FormView):
    template_name = 'register.html'
    form_class = RegisterForm

    def form_valid(self, form):
        data = form.cleaned_data
        user = User.objects.create_user(
            username=data['username'],
            password=data['password'],
            first_name = data['first_name'],
            last_name = data['last_name'],
            email=data['email']
        )
        user.profile.location = data['location']
        user.save()

        return HttpResponse('Вы зарегистрированы. Теперь Вам доступен личный кабинет на главной странице магазинa')

class DisplayDetailView(DetailView):
    template_name = 'profile_detail.html'
    model = Profile

BookStore/templates/users/profile_detail.html
{% extends 'base.html' %}
{% block title %}
<title>{{ object.user.username }}</title>
{% endblock title %}

{% block body %}
<div>
<h5>Пользователь : {{ object.user.username }}</h5>
<p><b>Имя:</b> {{ object.user.first_name }}</p>
<p><b>Фамилия:</b> {{ object.user.last_name }}</p>
<p><b>Email:</b> {{ object.user.email }}</p>
</div>

  <div class="collection">
        <a href="{% url 'book:book'  %}" class="blue-grey-text text-darken-2 collection-item">Посмотреть доступные книги на сайте</a>
        <a href="{% url 'refers:authors'  %}" class="blue-grey-text text-darken-2 collection-item">Посмотреть список авторов на сайте</a>
        <a href="{% url 'refers:series'  %}" class="blue-grey-text text-darken-2 collection-item">Посмотреть список серий на сайте</a>
        <a href="{% url 'refers:genres'  %}" class="blue-grey-text text-darken-2 collection-item">Посмотреть список жанров на сайте</a>
        <a href="{% url 'refers:publishinghouses'  %}" class="blue-grey-text text-darken-2 collection-item">Посмотреть список издательств на сайте</a>
        {% if perms.books.change_book %}
        <a href="{% url 'book:book'  %}" class="blue-grey-text text-darken-2 collection-item">Редактировать книги</a>
        {% endif %}
        {% if perms.book.add_book %}
        <a href="{% url 'book:book_create'  %}" class="blue-grey-text text-darken-2 collection-item">Добавить новую книгу</a>
        {% endif %}
        {% if perms.refers.add_authors %}
        <a href="{% url 'refers:authors_create'  %}" class="blue-grey-text text-darken-2 collection-item">Добавить нового автора</a>
        {% endif %}
        {% if perms.refers.add_series %}
        <a href="{% url 'refers:series_create'  %}" class="blue-grey-text text-darken-2 collection-item">Добавить новую серию</a>
        {% endif %}
        {% if perms.refers.add_genres %}
        <a href="{% url 'refers:genres_create'  %}" class="blue-grey-text text-darken-2 collection-item">Добавить новый жанр</a>
        {% endif %}
        {% if perms.refers.add_publishinghouses %}
        <a href="{% url 'refers:publishinghouses_create'  %}" class="blue-grey-text text-darken-2 collection-item">Добавить новое издательство</a>
        {% endif %}
      </div>

{% endblock body %}