BookStore/BookStore/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

BookStore/book/urls.py
from django.urls import path
from book.views import BookListView, BooksDetailView, BooksCreateView, BooksUpdateView, BooksDeleteView \

app_name = "book"

urlpatterns = [
    path('', BooksListView.as_view(), name = 'book'),
    path('detail/<int:pk>/', BooksDetailView.as_view(), name = 'book_detail'),
    path('create/', BooksCreateView.as_view(), name = 'book_create'),
    path('update/<int:pk>/', BooksUpdateView.as_view(), name = 'book_update'),
    path('delete/<int:pk>/', BooksDeleteView.as_view(), name = 'book_delete'),
]

BookStore/cart/urls.py
from django.urls import path
from .views import AddToCartUpdateView, CartListView, CartDeleteView, CartUpdateView

app_name = "cart"

urlpatterns = [
    path('add/<int:pk>/', AddToCartUpdateView.as_view(), name = "add"),
    path('', CartListView.as_view(), name="cart"),
    path('delete/<int:pk>/', CartDeleteView.as_view(), name='delete'),
    path('update/<int:pk>/', CartUpdateView.as_view(), name='update'),
]

BookStore/book/models.py
from django.db import models
from refers.models import Author,Serie,Genre

class Book(models.Model):
    title = models.CharField(max_length=100,blank=False, null=False)
    description = models.CharField(max_length=500,blank=True)
    cover = models.ImageField(upload_to='', blank=True)
    isbn = models.CharField(max_length=100, blank=True)
    author = models.ManyToManyField(
        Author,
    )
    serie = models.ForeignKey(
        Serie,
        on_delete=models.PROTECT
    )
    genre = models.ManyToManyField(
        Genre,
    )
    price = models.DecimalField(max_digits=5, decimal_places=2)
    cataloging = models.DateField(auto_now_add=True)
    last_change = models.DateField(auto_now=True)
    available_order = models.BooleanField(default=True)
    quantity = models.PositiveIntegerField(max_length=10)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name= "Book"
        verbose_name_plural = "Books"

    def get_absolute_url(self):
        return '/books/{self.pk}'

BookStore/book/forms.py
from django.forms import ModelForm
from book.models import Book

class BooksCreateForm(ModelForm):
    class Meta:
        model = Book
        fields = [
            'title',
            'price',
            'authors',
            'serie',
            'genres',
            'year_publishing',
            'pages',
            'binding',
            'format',
            'isbn',
            'weight',
            'age_restrictions',
            'publishing_house',
            'quantity',
            'rating',
            'available_order',
            'photo',
            'description',
        ]
class BooksUpdateForm(ModelForm):
    class Meta:
        model = Book
        fields = [
            'title',
            'price',
            'authors',
            'serie',
            'genres',
            'year_publishing',
            'pages',
            'binding',
            'format',
            'isbn',
            'weight',
            'age_restrictions',
            'publishing_house',
            'quantity',
            'rating',
            'available_order',
            'photo',
            'description',
        ]


class BooksDeleteForm(ModelForm):
    class Meta:
        model = Book
        fields = [
            'title',
            'price',
            'authors',
            'serie',
            'genres',
            'year_publishing',
            'pages',
            'binding',
            'format',
            'isbn',
            'weight',
            'age_restrictions',
            'publishing_house',
            'quantity',
            'rating',
            'available_order',
            'photo',
            'description',
        ]

BookStore/book/views.py
from django.views.generic import DetailView, ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from book.models import Book
from book.forms import BooksCreateForm, BooksUpdateForm, BooksDeleteForm
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin

class BooksListView(ListView):
    template_name = 'templates/BooksList.html'
    model = Book

class BooksDetailView(DetailView):
    template_name = 'templates/detail.html'
    model = Book

class BookCreateView(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    permission_required = 'book.add_book'
    model = Book
    form_class = BooksCreateForm
    template_name = 'templates/create.html'
    success_url = '/books'

class BooksUpdateView(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    permission_required = 'book.change_book'
    model = Book
    form_class = BooksUpdateForm
    template_name = 'templates/update.html'
    success_url = '/books'

class BooksDeleteView(LoginRequiredMixin, PermissionRequiredMixin, DeleteView):
    permission_required = 'book.delete_book'
    model = Book
    form_class = BooksDeleteForm
    template_name = 'templates/delete.html'
    success_url = 'books'

BookStore/templates/book/BooksList.html
{% extends 'base.html' %}

{% block title %}
<title>Список книг </title>
{% endblock title %}

{% block body %}
<table class="table">
  <thead class="thead-dark">
    <tr>
      <th scope="col">Номер</th>
      <th scope="col">Название</th>
      <th scope="col">Авторы</th>
      <th scope="col">Серия</th>
      <th scope="col">Описание</th>
      <th scope="col">Обложка</th>
      <th scope="col">Стоимость</th>
        {% if user.is_authenticated %}
      {% if perms.books.change_book %}
        <th scope="col">Редактировать</th>
      {% endif %}
        {% endif %}
    </tr>
  </thead>
  <tbody>
  {% for obj in object_list %}
    <tr>
      <td>{{obj.id}}</td>
      <td>{{obj.title}}</td>
      {% for author in obj.authors.all %}
      <td>{{author}}</td>
      {% endfor %}
      <td>{{obj.serie}}</td>
      <td>{{obj.description}}</td>
      <td><img src={{obj.photo.url}} width="70"  </td>
      <td>{{obj.price}} BYN</td>
        {% if user.is_authenticated %}
        {% if perms.books.change_book %}
        <td><a href="{% url 'book:book_update' obj.pk %}"><i class="material-icons">edit</i></a>
           {% endif %}
          {% if perms.books.delete_book %}
        <a href="{% url 'book:book_delete' obj.pk %}"><i class="material-icons">delete</a></td>
       {% endif %}
        {% endif %}
    </tr>
   {% endfor %}
  </tbody>
</table>
</table>
{% endblock body %}

BookStore/templates/book/create.html
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
{% load crispy_forms_tags %}

{% block title %}
{% endblock title %}

<h3>Добавить книгу</h3>
<form action='' method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{form|crispy}}
  <button type="submit" class="btn btn-success">Сохранить</button>
</form>

BookStore/templates/book/delete.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}
{% endblock title %}


{% block body %}
<form method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <p <h2> Вы уверены что хотите удалить  "{{ object }}" ? </h2></p>
    <button type="submit" class="blue-grey darken-2  btn btn-success">Подтвердить</button>
</form>
{% endblock body %}

BookStore/templates/book/detail.html
{% extends 'base.html' %}

{% block title %}
<title>{{object.title}}</title>
{% endblock title %}


{% block body %}

<ul class="list-group">
    <li class="list-group-item"><img src="{{object.photo.url}}" width="250" height="330"></li>
    <li class="list-group-item"><b>{{object.title}}</b></li>
    <li class="list-group-item"><b>Цена:</b>{{object.price}} BYN</li>
    {% for obj in object.authors.all %}
    <li class="list-group-item"><b>Авторы:</b>{{obj}}</li>
    {% endfor %}
    <li class="list-group-item"><b>Серия:</b>{{object.serie}}</li>
    {% for obj in object.genres.all %}
    <li class="list-group-item"><b>Жанр:</b>{{obj}}</li>
     {% endfor %}
    <li class="list-group-item"><b>Рейтинг:</b>{{object.description}}</li>
    <li class="list-group-item"><b>Дата издания:</b>{{object.year_publishing}}</li>
    <li class="list-group-item"><b>Количество страниц:</b>{{object.pages}}</li>
    <li class="list-group-item"><b>Переплет:</b>{{object.binding}}</li>
    <li class="list-group-item"><b>Формат:</b>{{object.format}}</li>
    <li class="list-group-item"><b>ISBN:</b>{{object.isbn}}</li>
    <li class="list-group-item"><b>Вес:</b>{{object.weight}}</li>
    <li class="list-group-item"><b>Возрастные ограничения:</b>{{object.age_restrictions}}</li>
    <li class="list-group-item"><b>Издательство:</b>{{object.publishing_house}}</li>
    <li class="list-group-item"><b>Количество:</b>{{object.quantity}}</li>
    <li class="list-group-item"><b>Рейтинг:</b>{{object.rating}}</li>
</ul>

{% endblock body %}

BookStore/templates/book/new.html
{% extends 'base.html' %}
{% block title %}
<title>Список книг </title>
{% endblock title %}

        <p class="z-depth-5">  <div class="card medium "></p>
              <div class="card-image waves-effect waves-block waves-light">
                    <a href="{% url 'book:book_detail' obj.pk %}"><img class="activator" src="{{obj.photo.url}}"></a>
                  <a href="{% url 'book:book_detail' obj.pk %}"><span class="card-title   indigo-text text-lighten-5 pulse">Подробнее</span></a>
                </div>
                <div class="card-content">
                    <p class="flow-text">{{obj.title}}</p>
                    <h7 class="  red-text text-darken-4">Добавить в корзину: {{obj.price}} BYN</h7>
                    <a href="{% url 'cart:add' obj.pk %}" class="btn-floating  blue-grey darken-3 pulse "><i class="material-icons">add</i></a>
                   <p <h7>{{obj.description}}</h7></p>
                </div>
            </div>
{% block pagination %}
  {% if is_paginated %}
      <div class="pagination">
          <span class="page-links">
              {% if page_obj.has_previous %}
                  <a href="{{ request.path }}?page={{ page_obj.previous_page_number }}" class="blue-grey darken-2 btn btn-secondary btn-sm">Назад</a>
              {% endif %}
              <span class="page-current">
                  <h6><p class="blue-grey-text text-darken-4">{{ page_obj.number }} из {{ page_obj.paginator.num_pages }}</p></h6>
              </span>
              {% if page_obj.has_next %}
                  <a href="{{ request.path }}?page={{ page_obj.next_page_number }}" class="blue-grey darken-2 btn btn-secondary btn-sm">Следующая</a>
              {% endif %}
          </span>
      </div>
  {% endif %}
{% endblock %}

BookStore/templates/book/popular.html
{% extends 'base.html' %}

{% block title %}
<title>Список книг </title>
{% endblock title %}


        <p class="z-depth-5">  <div class="card medium "></p>
              <div class="card-image waves-effect waves-block waves-light">
                    <a href="{% url 'book:book_detail' obj.pk %}"><img class="activator" src="{{obj.photo.url}}"></a>
                  <a href="{% url 'book:book_detail' obj.pk %}"><span class="card-title   indigo-text text-lighten-5 pulse">Подробнее</span></a>
                </div>
                <div class="card-content">
                    <p class="flow-text">{{obj.title}}</p>
                    <h7 class="  red-text text-darken-4">Добавить в корзину: {{obj.price}} BYN</h7>
                    <a href="{% url 'cart:add' obj.pk %}" class="btn-floating  blue-grey darken-3 pulse "><i class="material-icons">add</i></a>
                   <p <h7>{{obj.description}}</h7></p>
                </div>
            </div>

{% block pagination %}
  {% if is_paginated %}
      <div class="pagination">
          <span class="page-links">
              {% if page_obj.has_previous %}
                  <a href="{{ request.path }}?page={{ page_obj.previous_page_number }}" class="blue-grey darken-2 btn btn-secondary btn-sm">Назад</a>
              {% endif %}
              <span class="page-current">
                  <h6><p class="blue-grey-text text-darken-4">{{ page_obj.number }} из {{ page_obj.paginator.num_pages }}</p></h6>
              </span>
              {% if page_obj.has_next %}
                  <a href="{{ request.path }}?page={{ page_obj.next_page_number }}" class="blue-grey darken-2 btn btn-secondary btn-sm">Следующая</a>
              {% endif %}
          </span>
      </div>
  {% endif %}
{% endblock %}

BookStore/templates/book/update.html
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
{% load crispy_forms_tags %}


{% block title %}
<h1>Обновить</h1>
{% endblock title %}


{% block body %}
<form action='' method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class="btn btn-success">Обновить</button>
</form>
{% endblock body %}