BookStore/BookStore/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

BookStore/book/urls.py
from django.urls import path
from book.views import BookListView, BooksDetailView, BooksCreateView, BooksUpdateView, BooksDeleteView \

app_name = "book"

urlpatterns = [
    path('', BooksListView.as_view(), name = 'book'),
    path('detail/<int:pk>/', BooksDetailView.as_view(), name = 'book_detail'),
    path('create/', BooksCreateView.as_view(), name = 'book_create'),
    path('update/<int:pk>/', BooksUpdateView.as_view(), name = 'book_update'),
    path('delete/<int:pk>/', BooksDeleteView.as_view(), name = 'book_delete'),
]

BookStore/cart/urls.py
from django.urls import path
from .views import AddToCartUpdateView, CartListView, CartDeleteView, CartUpdateView

app_name = "cart"

urlpatterns = [
    path('add/<int:pk>/', AddToCartUpdateView.as_view(), name = "add"),
    path('', CartListView.as_view(), name="cart"),
    path('delete/<int:pk>/', CartDeleteView.as_view(), name='delete'),
    path('update/<int:pk>/', CartUpdateView.as_view(), name='update'),
]

BookStore/templates/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0"/>
    {% block title %}
    <title>Viajero</title>
    {% endblock title %}
    <!-- CSS  -->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link href="{% static 'css/materialize.css' %}" type="text/css" rel="stylesheet" media="screen,projection"/>
    <link href="{% static 'css/style.css' %}" type="text/css" rel="stylesheet" media="screen,projection"/>
</head>
<body>
<!-- Navbar-->
<nav class="blue-grey darken-4" role="navigation">
    <div class="nav-wrapper container"><a id="logo-container" href="/" class="brand-logo">Viajero Book</a>
        <ul class="right hide-on-med-and-down">
            <li><form action="{% url 'search_results' %}"   method="get">
            <input name="q" type="text white" placeholder="Поиск...">
            </form>
            </li>
            <li><a href="{% url 'book:book_new' %}">Новинки</a></li>
            <li><a href="{% url 'book:book_popular' %}">Популярное</a></li>
            {% if user.is_authenticated %}
            <font color="white">{{ user.get_username }}</font>
            <a href="{% url 'users:profile_detail' user.profile.pk %}" class="blue-grey darken-2 waves-effect waves-light btn-small"><i
                    class="material-icons right">account_circle</i>Личный кабинет</a>
            <a href="{% url 'cart:cart'  %}" class="blue-grey darken-2 waves-effect waves-light btn-small" ><i
                    class="material-icons right" >shopping_basket</i>Корзина</a>
            <a href="{% url 'logout'%}?next={{request.path}}" class="blue-grey darken-2 waves-effect waves-light btn-small" ><i
                    class="material-icons right" >exit_to_app</i>Выйти</a>
            {% else %}
            <a href="{% url 'users:create'%}" class="blue-grey darken-2 waves-effect waves-light btn-small "><i class="material-icons right">account_circle</i>Зарегистрироваться</a>
            <a href="{% url 'login'%}?next={{request.path}}" class="blue-grey darken-2 waves-effect waves-light btn-small"><i
                    class="material-icons right">account_circle</i>Войти</a>
            <a href="{% url 'cart:cart'  %}" class="blue-grey darken-2 waves-effect waves-light btn-small" ><i
                    class="material-icons right" >shopping_basket</i>Корзина</a>
            {% endif %}
        </ul>
    </div>
</nav>
{% block body %}
<div class="container">
    <div class="row">
        <!--   Icon Section   -->
        <div class="row">
        </div>
        {% for obj in object_list %}
        <div class="col s12 m4">{% include "card.html" %}</div>
        {% endfor %}
    </div>

{% block pagination %}
  {% if is_paginated %}
      <div class="pagination">
          <span class="page-links">
              {% if page_obj.has_previous %}
                  <a href="{{ request.path }}?page={{ page_obj.previous_page_number }}" class="blue-grey darken-2 btn btn-secondary btn-sm">Назад</a>
              {% endif %}
              <span class="page-current">
                  <h6><p class="blue-grey-text text-darken-4">{{ page_obj.number }} из {{ page_obj.paginator.num_pages }}</p></h6>
              </span>
              {% if page_obj.has_next %}
                  <a href="{{ request.path }}?page={{ page_obj.next_page_number }}" class="blue-grey darken-2 btn btn-secondary btn-sm">Следующая</a>
              {% endif %}
          </span>
      </div>
  {% endif %}
{% endblock %}

</div>
</div>
</div>
</div>
<br><br>
</div>
    {% block content %}
<footer class="page-footer">
    <div class="container">
        <div class="row">
            <div class="col l6 s12">
                <h5 class="white-text">Viajero Book Shop</h5>
                <p class="grey-text text-lighten-4">BELARUS, MINSK</p>
            </div>
            <div class="col l4 offset-l2 s12">
                <h5 class="white-text">Книжный магазин</h5>
                <ul>
                    <li><a class="grey-text text-lighten-3" >Курсы валют НБРБ на сегодня:</a></li>
                    <li><a class="grey-text text-lighten-3" >1 {{ usd.Cur_Abbreviation }} - {{ usd.Cur_OfficialRate }} BYN</a></li>
                    <li><a class="grey-text text-lighten-3" >1 {{ eur.Cur_Abbreviation }} - {{ eur.Cur_OfficialRate }} BYN</a></li>
                    <li><a class="grey-text text-lighten-3" >100 {{ rub.Cur_Abbreviation }} - {{ rub.Cur_OfficialRate }} BYN</a></li>
                </ul>
            </div>
        </div>
    </div>
    <div class="footer-copyright">
        <div class="container">
            © 2019 Pavel Liurts
        </div>
    </div>
</footer>
    {% endblock content %}
<!--  Scripts-->
<script src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
<script src="{% static 'js/materialize.js' %}"></script>
<script src="{% static 'js/init.js' %}"></script>
</body>
{% endblock body %}
</html>

BookStore/templates/card.html
          <p class="z-depth-5">  <div class="card medium "></p>
              <div class="card-image waves-effect waves-block waves-light">
                    <a href="{% url 'book:book_detail' obj.pk %}"><img class="activator" src="{{obj.photo.url}}"></a>
                  <a href="{% url 'book:book_detail' obj.pk %}"><span class="card-title   indigo-text text-lighten-5 pulse">Подробнее</span></a>
                </div>
                <div class="card-content">
                    <p class="flow-text">{{obj.title}}</p>
                    {% for author in obj.authors.all %}
                     <p<h7>{{author}}</h7></p>
                    {% endfor %}
                    <h7 class="  red-text text-darken-4">Добавить в корзину: {{obj.price}} BYN</h7>
                    <a href="{% url 'cart:add' obj.pk %}"  class="btn-floating  blue-grey darken-3 pulse "><i class="material-icons">add</i></a>
                   <p <h7>{{obj.description}}</h7></p>
                </div>
            </div>

BookStore/templates/register.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}


{% block body %}
<h4>Заполните необходимые поля</h4>

<form method="post">
    {% csrf_token %}
    <div class="form-group row">
        <label for="staticUser"  class="col-sm-2 col-form-label blue-grey-text text-darken-4">Введите имя пользователя</label>
        <div class="form-group col-md-6 mb-0">
            <input type={{form.username}}
        </div>
    <div class="form-group row">
        <label for="inputEmail" class="col-sm-2 col-form-label blue-grey-text text-darken-4">Введите email</label>
        <div class="col-sm-10">
            <input type={{form.email}}
        </div>
        <div class="form-group row">
            <label for="inputFirstName" class="col-sm-2 col-form-label blue-grey-text text-darken-4">Введите Имя</label>
            <div class="col-sm-10">
                <input type={{form.first_name}}
            </div>
            <div class="form-group row">
                <label for="inputLastName" class="col-sm-2 col-form-label blue-grey-text text-darken-4">Фамилию</label>
                <div class="col-sm-10">
                    <input type={{form.last_name}}
                </div>
                <div class="form-group row">
                    <label for="inputPassword" class="col-sm-2 col-form-label blue-grey-text text-darken-4">Введите пароль</label>
                    <div class="col-sm-10">
                        <input type={{form.password}}
                    </div>
                    <div class="form-group row">
                        <label for="inputLocation" class="col-sm-2 col-form-label blue-grey-text text-darken-4">Введите город</label>
                        <div class="col-sm-10">
                            <input type={{form.location}}
                        </div>
                    </div>
                    <button type="submit" class=" blue-grey darken-2 waves-effect waves-light btn-small">Сохранить</button>
</form>
{% endblock body %}