BookStore/BookStore/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

BookStore/book/urls.py
from django.urls import path
from book.views import BookListView, BooksDetailView, BooksCreateView, BooksUpdateView, BooksDeleteView \

app_name = "book"

urlpatterns = [
    path('', BooksListView.as_view(), name = 'book'),
    path('detail/<int:pk>/', BooksDetailView.as_view(), name = 'book_detail'),
    path('create/', BooksCreateView.as_view(), name = 'book_create'),
    path('update/<int:pk>/', BooksUpdateView.as_view(), name = 'book_update'),
    path('delete/<int:pk>/', BooksDeleteView.as_view(), name = 'book_delete'),
]

BookStore/refers/urls.py
from django.urls import path
from refers.views import AuthorListView, AuthorDetailView, AuthorCreateView, AuthorDeleteView, AuthorUpdateView, \
    SerieListView, SerieDetailView, SerieCreateView, SerieDeleteView, SerieUpdateView, GenreListView, \
    GenreDetailView, GenreCreateView, GenreUpdateView, GenreDeleteView

app_name = "refers"

urlpatterns = [
    path('authors/', AuthorListView.as_view(), name='authors'),
    path('<int:pk>/', views.AuthorDetailView.as_view(), name='authors_detail'),
    path('authors/create/', views.AuthorCreateView.as_view(), name='authors_create'),
    path('delete/<int:pk>/', views.AuthorDeleteView.as_view(), name='authors_delete'),
    path('update/<int:pk>/', views.AuthorUpdateView.as_view(), name='authors_update'),
    path('series/', views.SerieListView.as_view(), name='series'),
    path('<int:pk>/', views.SerieDetailView.as_view(), name='series_detail'),
    path('series/create/', views.SerieCreateView.as_view(), name='series_create'),
    path('delete/<int:pk>/', views.SerieDeleteView.as_view(), name='series_delete'),
    path('update/<int:pk>/', views.SerieUpdateView.as_view(), name='series_update'),
    path('genres/', views.GenreListView.as_view(), name='genres'),
    path('<int:pk>/', views.GenreDetailView.as_view(), name='genres_detail'),
    path('genres/create/', views.GenreCreateView.as_view(), name='genres_create'),
    path('delete/<int:pk>/', views.GenreDeleteView.as_view(), name='genres_delete'),
    path('update/<int:pk>/', views.GenreUpdateView.as_view(), name='genres_update'),
]

BookStore/refers/models.py
from django.db import models

class Author(models.Model):
    name = models.CharField(max_length=100, blank=False, null=False)

    class Meta:
        verbose_name = "Author"
        verbose_name_plural = "Authors"

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return f'/authors/{self.pk}'

class Serie(models.Model):
    name = models.CharField(max_length=100, blank=False, null=False)

    class Meta:
        verbose_name = "Serie"
        verbose_name_plural = "Serie"

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return f'/series/{self.pk}'

class Genre(models.Model):
    name = models.CharField(max_length=100, blank=False, null=False)

    class Meta:
        verbose_name = "Genre"
        verbose_name_plural = "Genres"

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return f'/genres/{self.pk}'

BookStore/refers/forms.py
from django.forms import ModelForm
from refers.models import Author, Serie, Genre

class AuthorCreateForm(ModelForm):
    class Meta:
        model = Author
        fields = [
            'name'
        ]

class AuthorDeleteForm(ModelForm):
    class Meta:
        model = Author
        fields = [
            'name'
        ]

class AuthorUpdateForm(ModelForm):
    class Meta:
        model = Author
        fields = [
            'name'
        ]


class SerieCreateForm(ModelForm):
    class Meta:
        model = Author
        fields = [
            'name'
        ]


class SerieDeleteForm(ModelForm):
    class Meta:
        model = Author
        fields = [
            'name'
        ]


class SerieUpdateForm(ModelForm):
    class Meta:
        model = Author
        fields = [
            'name'
        ]


class GenreCreateForm(ModelForm):
    class Meta:
        model = Author
        fields = [
            'name'
        ]


class GenreDeleteForm(ModelForm):
    class Meta:
        model = Author
        fields = [
            'name'
        ]


class GenreUpdateForm(ModelForm):
    class Meta:
        model = Author
        fields = [
            'name'
        ]

BookStore/refers/views.py
from django.views.generic import DetailView, ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from refers.models import Author, Serie, Genre
from refers.forms import AuthorCreateForm, AuthorDeleteForm, AuthorUpdateForm, SerieCreateForm,SerieDeleteForm,SerieUpdateForm, GenreCreateForm, GenreDeleteForm, GenreUpdateForm
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin

class AuthorListView(ListView):
    template_name = 'templates/AuthorList.html'
    model = Author

class AuthorDetailView(DetailView):
    template_name = 'templates/detail.html'
    model = Author

class AuthorCreateView(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    permission_required = 'refers.add_authors'
    model = Author
    form_class = AuthorCreateForm
    template_name = 'templates/create.html'
    success_url = '/authors'

class AuthorUpdateView(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    permission_required = 'refers.change_authors'
    model = Author
    form_class = AuthorUpdateForm
    template_name = '/templates/update.html'
    success_url = '/authors'

class AuthorDeleteView(LoginRequiredMixin, PermissionRequiredMixin, DeleteView):
    permission_required = 'refers.delete_authors'
    model = Author
    form_class = AuthorDeleteForm
    template_name = 'templates/delete.html'
    success_url = '/authors'


class SerieListView(ListView):
    template_name = 'templates/SerieList.html'
    model = Serie


class SerieDetailView(DetailView):
    template_name = 'templates/detail.html'
    model = Serie


class SerieCreateView(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    permission_required = 'refers.add_series'
    model = Serie
    form_class = SerieCreateForm
    template_name = 'templates/create.html'
    success_url = '/series'


class SerieUpdateView(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    permission_required = 'refers.change_series'
    model = Serie
    form_class = SerieUpdateForm
    template_name = '/templates/update.html'
    success_url = '/series'


class SerieDeleteView(LoginRequiredMixin, PermissionRequiredMixin, DeleteView):
    permission_required = 'refers.delete_series'
    model = Serie
    form_class = SerieDeleteForm
    template_name = 'templates/delete.html'
    success_url = '/series'

class GenreListView(ListView):
    template_name = 'templates/GenreList.html'
    model = Genre


class GenreDetailView(DetailView):
    template_name = 'templates/detail.html'
    model = Genre


class GenreCreateView(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    permission_required = 'refers.add_genres'
    model = Genre
    form_class = GenreCreateForm
    template_name = 'templates/create.html'
    success_url = '/genre'


class GenreUpdateView(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    permission_required = 'refers.change_genres'
    model = Genre
    form_class = GenreUpdateForm
    template_name = '/templates/update.html'
    success_url = '/genres'


class GenreDeleteView(LoginRequiredMixin, PermissionRequiredMixin, DeleteView):
    permission_required = 'refers.delete_genres'
    model = Genre
    form_class = GenreDeleteForm
    template_name = 'templates/delete.html'
    success_url = '/genres'

BookStore/templates/refers/AuthorsList.html
{% extends 'base.html' %}

{% block title %}
{% endblock title %}

{% block body %}
<h3>Список авторов </h3>
<table class="table">
  <thead class="thead-dark">
    <tr>
      <th scope="col">Номер</th>
      <th scope="col">Автор</th>
        {% if user.is_authenticated %}
      {% if perms.refers.change_authors %}
        <th scope="col">Редактировать</th>
       {% endif %}
        {% endif %}
    </tr>
  </thead>
  <tbody>
  {% for obj in object_list %}
    <tr>
      <th scope="row">{{obj.id}}</th>
      <td>{{obj.name}}</td>
        {% if user.is_authenticated %}
      {% if perms.refers.change_authors %}
        <td><a href="{% url 'refers:authors_update' obj.pk %}"><i class="material-icons">edit</i></a>
            {% endif %}
          {% if perms.refers.delete_authors %}
        <a href="{% url 'refers:authors_delete' obj.pk %}"><i class="material-icons">delete</a></td>
      {% endif %}
        {% endif %}
    </tr>
   {% endfor %}
  </tbody>
</table>
</table>
{% endblock body %}

BookStore/templates/refers/GenresList.html
{% extends 'base.html' %}

{% block title %}
{% endblock title %}

{% block body %}
<h3>Список жанров</h3>
<table class="table">
  <thead class="thead-dark">
    <tr>
      <th scope="col">Номер</th>
      <th scope="col">Автор</th>
        {% if user.is_authenticated %}
      {% if perms.refers.change_genres %}
        <th scope="col">Редактировать</th>
      {% endif %}
        {% endif %}
    </tr>
  </thead>
  <tbody>
  {% for obj in object_list %}
    <tr>
      <th scope="row">{{obj.id}}</th>
      <td>{{obj.name}}</td>
        {% if user.is_authenticated %}
      {% if perms.refers.change_genres %}
        <td><a href="{% url 'refers:genres_update' obj.pk %}"><i class="material-icons">edit</i></a>
          {% endif %}
          {% if perms.refers.delete_genres %}
        <a href="{% url 'refers:genres_delete' obj.pk %}"><i class="material-icons">delete</a></td>
      {% endif %}
        {% endif %}
    </tr>
   {% endfor %}
  </tbody>
</table>
</table>
{% endblock body %}

BookStore/templates/refers/Publishing_housesList.html
{% extends 'base.html' %}

{% block title %}
{% endblock title %}

{% block body %}
<h3>Список издательств</h3>
<table class="table">
  <thead class="thead-dark">
    <tr>
      <th scope="col">Номер</th>
      <th scope="col">Издательство</th>
        {% if user.is_authenticated %}
      {% if perms.refers.change_publishinghouses %}
        <th scope="col">Редактировать</th>
       {% endif %}
        {% endif %}
    </tr>
  </thead>
  <tbody>
  {% for obj in object_list %}
    <tr>
      <th scope="row">{{obj.id}}</th>
      <td>{{obj.name}}</td>
        {% if user.is_authenticated %}
        {% if perms.refers.change_publishinghouses %}
        <td><a href="update/{{obj.pk}}"><i class="material-icons">edit</i></a>
           {% endif %}
          {% if perms.refers.delete_publishinghouses %}
        <a href="delete/{{obj.pk}}"><i class="material-icons">delete</a></td>
      {% endif %}
        {% endif %}
    </tr>
   {% endfor %}
  </tbody>
</table>
</table>
{% endblock body %}

BookStore/templates/refers/SeriesList.html
{% extends 'base.html' %}

{% block title %}
{% endblock title %}

{% block body %}
<h3>Список серий</h3>
<table class="table">
  <thead class="thead-dark">
    <tr>
      <th scope="col">Номер</th>
      <th scope="col">Серияр</th>
        {% if user.is_authenticated %}
            {% if perms.refers.change_series %}
        <th scope="col">Редактировать</th>
       {% endif %}
        {% endif %}
    </tr>
  </thead>
  <tbody>
  {% for obj in object_list %}
    <tr>
      <th scope="row">{{obj.id}}</th>
      <td>{{obj.name}}</td>
        {% if user.is_authenticated %}
      {% if perms.refers.change_series %}
        <td><a href="{% url 'refers:series_update' obj.pk %}"><i class="material-icons">edit</i></a>
          {% endif %}
          {% if perms.refers.delete_series %}
        <a href="{% url 'refers:series_delete' obj.pk %}"><i class="material-icons">delete</a></td>
       {% endif %}
        {% endif %}
    </tr>
   {% endfor %}
  </tbody>
</table>
</table>
{% endblock body %}

BookStore/templates/refers/create.html
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
{% load crispy_forms_tags %}
{% load crispy_forms_tags %}

{% block title %}
{% endblock title %}

{% block body %}
<h5>Введите значение</h5>
<form method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class="btn btn-success">Подтвердить</button>
</form>
{% endblock body %}

BookStore/templates/refers/delete.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}


{% block title %}
{% endblock title %}


{% block body %}
<h4>Удалить</h4>
<p method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <p<h6> Вы уверены что хотите удалить  "{{ object }}" ?</h6></p>
    <button type="submit" class=" blue-grey darken-2 btn btn-success">Подтвердить</button>
</form>
{% endblock body %}

BookStore/templates/refers/update.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}


{% block title %}
{% endblock title %}


{% block body %}
<h4>Обновить</h4>
<form method="post">
    {% csrf_token %}
    {{ form|crispy }}
     <p<h6> Введите новое значение для  "{{ object }}" и нажмите "Обновить"</h6></p>
    <button type="submit" class="blue-grey darken-2  btn btn-success">Обновить</button>
</form>
{% endblock body %}